- hosts: win
  gather_facts: yes
  vars_files:
    - group_vars/windows/vars_win.yml
    - group_vars/windows/vault_win.yml
    - host_vars/windows/host_vars_win.yml
  tasks:
  - name: Change the hostname
    win_hostname:
      name: "{{ hostname}}"
    register: res

  - name: Reboot
    win_reboot:
    when: res.reboot_required

  - name: wait 5 min  until reboot complete
    wait_for:
      timeout: 300
    delegate_to: localhost
        
  - name: Configure Primary DNS Server
    win_dns_client:
      adapter_names: 'Ethernet 2'
      ipv4_addresses:
        - 192.168.0.3        
  - name: join server to domain
    win_domain_membership:
      dns_domain_name: "{{ dns_domain_name }}"
      hostname: "{{ ansible_hostname }}"
      domain_admin_user: "{{ domain_admin_user }}"
      domain_admin_password: "{{ domain_admin_password }}"
      #      domain_ou_path: "OU=Windows,OU=Servers,DC=ansiwin,DC=local"
      state: domain
    register: domain_state

  - win_reboot:
    when: domain_state.reboot_required
