---
# tasks file for domain-controller
  - name: install ad
    win_feature: 
      name: AD-Domain-Services
      include_management_tools: yes
      include_sub_features: yes
      state: present
    register: result
  - name: Create new domain in a new forest on the target host
    win_domain:
      dns_domain_name: '{{ dns_domain_name }}'
      safe_mode_password: '{{ safe_mode_password }}'
    register: domain_install
  - name: Reboot if necessary
    win_reboot:
      msg: "Installing AD. Rebooting..."
    when: domain_install.reboot_required